### ISSUE TITLE
By any change can we see the code of the multi step wizard?

### ISSUE THREAD

**Issue by Jarrodsz** [theodorusclarence/rhf-input#7]
By any change can we see the code of the multi step wizard?
Its not in the repo have been trying for ages to get it to work, is the source available somewhere? 
Kind regards.

Also some installation instructions would be nice, I have no idea how to integrate your components with my app based on the documentation. Kind regards

**Comment by theodorusclarence** [comment]
Hey, you can actually click the heading of the page or visit https://github.com/theodorusclarence/rhf-stepform
![D7F89CBE-E045-4326-99F7-B28CFB194834](https://user-images.githubusercontent.com/55318172/137416681-85038cf6-4cd4-4476-a5c1-f24eff662d4d.png)

**Comment by Jarrodsz** [comment]
Thank you It did not underline on my browser and totally missed it. Thank you for sharing a great learning resource on how to do forms correctly

**Comment by theodorusclarence** [comment]
Pleasure @Jarrodsz ! 
Oof, can you give some information about your browser and device? I might need to check that out.
